Ignoring non-zero return value during deploy

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,7 +24,7 @@ before_deploy:
 - eval "$(ssh-agent -s)"
 - chmod 600 /tmp/deploy_rsa_2018-02-02
 - ssh-add /tmp/deploy_rsa_2018-02-02
-- eval "ssh-keygen -F $REMOTE_HOST 2>/dev/null 1>/dev/null"
+- eval "ssh-keygen -F $REMOTE_HOST 2>/dev/null 1>/dev/null" || true # Ignoring non-zero return value
 - if [ $? -eq 0 ]; then
     echo “$REMOTE_HOST is already known”
   else
